export declare enum UserStatus {
    APPLIED = "APPLIED",
    INVITED = "INVITED",
    TEST_TAKEN = "TEST_TAKEN",
    INTERVIEW_TAKEN = "INTERVIEW_TAKEN",
    REJECTED = "REJECTED",
    SIGNED_ISA = "SIGNED_ISA",
    ISA_REJECTED = "ISA_REJECTED",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE"
}
